language: scala

scala:
  - "2.11.12"
  - "2.12.6"
  - "2.13.0-M3"

sudo: false

script:
  - sbt ++$TRAVIS_SCALA_VERSION jvmRoot/clean jvmRoot/test
  - sbt ++$TRAVIS_SCALA_VERSION jsRoot/clean jsRoot/test

after_success:
  # Snapshot publishing via Travis (only for authoritative repo and on master branch) courtesy of Jan Machacek, thanks!
  # http://www.cakesolutions.net/teamblogs/publishing-artefacts-to-oss-sonatype-nexus-using-sbt-and-travis-ci
  - "[[ \"$TRAVIS_REPO_SLUG\" == \"wix/accord\" ]] && [[ \"$TRAVIS_BRANCH\" == \"master\" ]] && { sbt \"++$TRAVIS_SCALA_VERSION publish\"; };"

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10

env:
  global:
    - secure: "TRDTLUiwGoI1O0dcP6F96Djb7xlRlaowrEWMrL+lUZizlCiSJ3/RdqDDGspzS8NQkBRXrqHhyTf2RIwfxu3J0nstlzfTwEpNhF698EhpHVVR9srBsgr8+iinS5WCUcotrMKDWIOpLPERbw9tap3HJQPJiXAUDqzPixjThb/BpXg="
    - secure: "U22HGF01uu6rruU+M2y6dokf2EHM5d9r/VxwSPRrxW6m34KlVhIfPtuobo+mAfwDRC25+nedPe/YWcPRm50kbX7pYzGVHAkP1A2SIJXVkvqmQb1qezu1D3qu3mSHoZbvLvWVUJX0ige7QHOfAW2lypIFFDJcbiwXqZN3q4IB+bs="

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d3c83757dec6f0aa0382
    on_success: change
    on_failure: always
    on_start: never

# Cache bootstrap and dependency files for (hopefully) faster builds, per recommendation in
# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers/

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

